# trading period
freq: 'w'
# csv filename
csv_file_returns: 'db/returns.csv'
csv_file_prices: 'db/prices.csv'
# first trading date
start_date: "2010-01-01"
# number of training episodes
num_episodes: 10000
# tickers
tickers:
  - 'AAPL'
  - 'GE'
  - 'JPM'
  - 'GOOG'
  - 'MSFT'
  - 'VOD'
  - 'GS'
  - 'TSLA'